"""add region to listings

Revision ID: 2b1a80f872a3
Revises: 444d324a984a
Create Date: 2026-07-29 15:19:36.320926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1a80f872a3'
down_revision: Union[str, Sequence[str], None] = '444d324a984a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('region', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_listings_region'), 'listings', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_region'), table_name='listings')
    op.drop_column('listings', 'region')
    # ### end Alembic commands ###
